let extention = {
    "python": ".py",
    "javascript": ".js",
    "java": ".java",
    "c": ".c",
    "c++": ".cpp",
    "c#": ".cs",
    "php": ".php",
    "ruby": ".rb",
    "swift": ".swift",
    "kotlin": ".kt",
    "typescript": ".ts",
    "go": ".go",
    "rust": ".rs",
    "scala": ".scala",
    "perl": ".pl",
    "r": ".r",
    "matlab": ".m",
    "html/css": [".html", ".css"], 
    "sql": ".sql",
    "bash": ".sh",
    "dart": ".dart",
    "objective-c": ".m",
    "elm": ".elm",
    "elixir": ".ex",
    "clojure": ".clj",
    "f#": ".fs",
    "apex": ".cls",
    "pl/sql": ".sql",
    "solidity": ".sol",
    "t-sql": ".sql",
    "tcl": ".tcl",
    "groovy": ".groovy",
    "powershell": ".ps1",
    "vhdl": ".vhd",
    "verilog": ".v",
    "assembly": ".asm",
    "lua": ".lua",
    "awk": ".awk",
    "sed": ".sed"
}

export default extention;